name: Build

on:
  push:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build EBOOT.PBP
        run: |
          mkdir build && cd build
          psp-cmake ..
          make -j $(getconf _NPROCESSORS_ONLN)
          echo ${{github.sha}} > SHA.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: false
          prerelease: false
          files: |
            build/SHA.txt
            build/EBOOT.PBP
