name: Build

on:
  push:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build EBOOT.PBP
        run: |
          psp-cmake ${{github.workspace}}
          make ${{github.workspace}}
          echo ${{ github.sha }} > SHA.txt
          cat SHA.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            SHA.txt
            EBOOT.PBP
