name: Build

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build EBOOT.PBP
        run: |
          cd build
          psp-cmake ..
          make -j $(getconf _NPROCESSORS_ONLN)
          echo ${{github.sha}} > SHA.txt

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "psp-controller"
          files: |
            SHA.txt
            build/EBOOT.PBP
